### PR TITLE
MIST-564 Log deferred errors instead of ignoring

### PR DESCRIPTION
**Pull request by TauZero**
[Review on Reviewable](https://reviewable.io/reviews/mistifyio/kvite/13)

### CODE REVIEW

**Comment by TauZero** [comment]
Ok to test

**Comment by trisk** [comment]
<sup>**[kvite_test.go, line 315 \[r1\]](https://reviewable.io:443/reviews/mistifyio/kvite/13#-JyOqUq1IBXl61Gxrxgk)** ([raw file](https://github.com/mistifyio/kvite/blob/adb8c483e126a6fbe134bd553d7777235de31725/kvite_test.go#L315)):</sup>
Looks like the argument, `file` is accidentally clobbered here.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/kvite/13)

**Comment by TauZero** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[kvite_test.go, line 315 \[r1\]](https://reviewable.io:443/reviews/mistifyio/kvite/13#-JyOqUq1IBXl61Gxrxgk)** ([raw file](https://github.com/mistifyio/kvite/blob/adb8c483e126a6fbe134bd553d7777235de31725/kvite_test.go#L315)):</sup>
You're right. Fixed.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/kvite/13)

**Comment by mmlb** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/kvite/13)

**Comment by trisk** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/kvite/13)

**Pull request merged**
